<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanghe.fs</groupId>
        <artifactId>fs-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>fs-system</artifactId>

    <description>
        fs-system - 系统管理模块，负责用户、角色、权限等系统管理功能
    </description>

    <dependencies>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-storage</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>

</project>
