<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanghe.fs</groupId>
        <artifactId>gfs</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>fs-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        fs-modules - 业务模块集合，包含各个业务功能模块
    </description>

    <modules>
        <module>fs-storage</module>
        <module>fs-system</module>
        <module>fs-log</module>
        <module>fs-file</module>
        <module>fs-service</module>
    </modules>
</project>
