<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanghe.fs</groupId>
        <artifactId>fs-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>fs-storage</artifactId>

    <description>
        fs-storage - 存储管理模块，负责文件存储和多种存储平台的集成
    </description>

    <dependencies>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>fs-swagger</artifactId>
        </dependency>

        <!-- 存储插件依赖 -->
        <dependency>
            <groupId>com.guanghe.fs</groupId>
            <artifactId>storage-plugin-boot</artifactId>
        </dependency>
    </dependencies>

</project>
